const express = require('express');
const { authRequired, requirePermission } = require('../middleware/auth');
const admin = require('../controllers/adminController');
const tlsCertificates = require('../controllers/tlsCertificateController');
const router = express.Router();
router.use(authRequired);
router.get('/uploads', requirePermission('REPORT_READ_ALL_METADATA'), admin.listAllUploads);
router.get('/rejected-uploads', requirePermission('REJECTED_UPLOADS_VIEW'), admin.listRejectedUploads);
router.get('/certificates', requirePermission('CERT_VIEW_ALL'), admin.listCertificates);
router.get('/revoked-certificates', requirePermission('CERT_VIEW_ALL'), admin.listRevokedCertificates);
router.post('/issue-certificate', requirePermission('CERT_ISSUE'), admin.issueCertificate);
router.post('/rotate-certificate', requirePermission('CERT_ISSUE'), admin.rotateCertificate);
router.post('/revoke-certificate', requirePermission('CERT_REVOKE'), admin.revokeCertificate);
router.delete('/revoked-certificates/:serialNumber', requirePermission('CERT_REVOKE'), admin.unrevokeCertificate);
router.get('/users', requirePermission('USER_MANAGE'), admin.listUsers);
router.get('/patient-assignments', requirePermission('PATIENT_ASSIGN'), admin.listAssignments);
router.post('/assign-patient', requirePermission('PATIENT_ASSIGN'), admin.assignPatient);
router.post('/tls-certificates/issue', requirePermission('TLS_CERT_ISSUE'), tlsCertificates.issue);
router.get('/tls-certificates', requirePermission('TLS_CERT_VIEW_ALL'), tlsCertificates.list);
router.get('/tls-certificates/:serialNumber', requirePermission('TLS_CERT_VIEW_ALL'), tlsCertificates.detail);
router.post('/tls-certificates/:serialNumber/revoke', requirePermission('TLS_CERT_REVOKE'), tlsCertificates.revoke);
router.post('/tls-certificates/:serialNumber/rotate', requirePermission('TLS_CERT_ISSUE'), tlsCertificates.rotate);
module.exports = router;
